### ISSUE TITLE
用Spring的Reactor写项目看看速度怎么样

### ISSUE THREAD

**Issue by artshell** [xenv/gushici#1]
https://www.infoq.com/articles/Servlet-and-Reactive-Stacks-Spring-Framework-5
https://github.com/reactor/reactor-core
https://www.infoq.com/articles/reactor-by-example

**Comment by xenv** [comment]
谢谢， Spring WebFlux 我在关注，据一些评测说性能比 Vert.x 稍差，还没有实际测试。到时候有机会再入坑。

**Comment by xenv** [comment]
新版本出来了，用了 webflux，速度一般般吧，也可能是业务逻辑变复杂了
[https://www.jinrishici.com](https://www.jinrishici.com)

**Comment by artshell** [comment]
@xenv 为言出必行，点赞
