### ISSUE TITLE
跨域问题 access-control-allow-origin 多个

### ISSUE THREAD

**Issue by Cotch22** [xenv/gushici#19]
![image](https://user-images.githubusercontent.com/24957558/205012279-fd3984d2-b065-4b7a-bf1a-01330d6c8ef9.png)

突然出现的，是不是调整了接口
目前测试直接访问也会带上
`access-control-allow-origin： *`

跨域请求就会出现两个相同 header 的报错

**Comment by xenv** [comment]
谢谢提醒，修复了
