### ISSUE TITLE
服务器貌似挂了

### ISSUE THREAD

**Issue by KaiOrange** [xenv/gushici#5]

**Comment by xenv** [comment]
谢谢关注。

由于 api.gushi.ci 不能备案，之前通过 https 的方式绕过备案检测，不过最近该方法失效，导致域名不能访问。

为了继续保持良好的网络服务。现将 `api.gushi.ci` 域名修改为 `v1.jinrishici.com` ，调用路径，方法不变。

旧 api.gushi.ci 服务器已迁移至香港，已恢复并会继续提供服务。2019 年 12 月 1 日起，接口将会自动跳转到 v1.jinrishici.com 。如果您暂时不想修改或者无法修改，接口也基本可用。12 月 1 日后，如果您的调用环境不支持自动跳转（如部分单片机），服务可能会受到影响。十分抱歉给您带来不便， 感谢您的理解。

所以，您需要将调用代码里面的 `api.gushi.ci` 修改为 `v1.jinrishici.com`
